name: go-build-kubectl

on:
  push:
    branches: [ main ]

  schedule:
    - cron: "3 4 * * 0"

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        include:
          - platform: ubuntu-latest

    name: Build ${{ join(matrix.platform, ',') }} 
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          role-to-assume: arn:aws:iam::973800055156:role/kubectl-github-runner
          aws-region: eu-central-1
          role-session-name: GitHubAction

      - shell: bash
        name: build.sh
        run: |
          bash -x build.sh


